### ISSUE TITLE
a bytes-like object is required, not 'str'

### ISSUE THREAD

**Issue by 0xEEEEEE** [JohnTroony/Blisqy#2]
I have configured the target detail and I am trying to run the FindBlindSpot against a target and I am keep getting message below
```
python3 FindBlindSpot.py 
[+] Fuzzer Running  : target.local:443

a bytes-like object is required, not 'str'
```
I've only changed the Server and Port parameters.

**Comment by JohnTroony** [comment]
Hey there, seems like you are using Python 3. Run `which python` on your terminal and share your output. Otherwise, I'd like to help fix any issue with the code. Thanks.

**Comment by JohnTroony** [comment]
I'm closing this issue. Confirmed, Blisqy is working fine under Python 2.7*.
